language: node_js
node_js: 12
install:
  - npm install
script:
  - npm run lint
  - npm run i18n_extract
  - npm run test
  - npm run build
after_success:
  - npx semantic-release
  - codecov
env:
  global:
  # GH_TOKEN
  - secure: "rsp0BAOafslXUGAZRkE5KS3Vw+orqyxrLe3TbDilS6xnQGCv0XbHuHVaOgc7LiUVz7jbNC0gqEm+s0K1XVCxf/J6bTFIyfYILX6A1rGbDSdZuP0a2xrfK1VIM7tYvDwmkqxaOA9t8jl0pjyYK9Wh9xti+SZnlv8x8kthpM6I2cU+jdD3JsQ+0q2sylARog/E51Y6JfG1LkFbned+k4WG1Q+DHEwrp0mEv3e9e/ZwFPh2NXAAOR7NOb80HUrcaoBXO5VshaD4+rOJM25Q+WmuDAU8t4X7RSmgZCxLAmVmWMYijVnRKLCImDsUZuxkSp2I5mzB4PkLglyr37amK+K8aLBDWk4AHNpsZ4nyuDH9I0tHWXV8L74lXnF17EX7nnnP67YmKijxkWEdjTxjM+i6Jx0ndQwvV0zhXQkAm8nMJL7pI6nvsUsMV7U/HAHRxaIH/1G1sWIFNMN8taSlAhauHkbIawpluViaHwDCczO3aH9wgcgozoEACgp6EFlyUD2QwDfTLXwr4bU0EH7JaQbWwWzBmWTRY4I3h6U+/ppbq/e5pvKL0jsAKW7dXrcd248OuFT45L1juxaIAMTU0yrI8VOXxsx1jN31fuuotXH5SOqxwOyhCFOrxlmkaWtTDjbXQtJO4fSbwjvFX4BAPDhTRUHKvkSFNLO649aRmHpt0E4="
  # NPM_TOKEN
  - secure: "rijCyj/L5J+aPwnL8EjUjTgVVynHTH110EhTvBe6xfMZVSU8qZPzAITydQysqRUNPp3991WNABgWecPJEJo+V6Byxa0NUgv6SyTIY8w8FQUaKmVwMtmDn7tdnd1/7/RJEI4UUUjgCtWxMbJ9Akv9mecpcUKGuE9c3HqwZLnZvIFnBC6p3g2QUJlWgvvUs91O+uvHvVVG7qTseXNkEeF7XOJAVozKz9qO2Hp3A/wZobUXq163LmFMgLlmysnk7nXS/3xi35sxJk0gpoeBrfy7QFWJtIkvRKNFpDMP0xKpE/gy9Iy7BoJnvnNdNuXYPxJ+zMSSwvws00Jy/ARi4TgMyJ38VVZ6lSgTp8bWrL5TsIEngnGphgMHrGQsyj/aE1mj4XNQbz6AL2xarp3y63RwpfTsXJxlqSMqw2wSN8vO9+ToJBEoiND4dgP3LDUvQCT+A15crBrQtXoONoNQruDmCh0+sbAu+/NEyjBwJuJr4oDSQNB221TtXpuLA1DeSyyRfw0vxKgU3M8IFSm89kjvU/Nn+qj/YLzqrC9RgXifhTLcBSgAHEiezlzagFWPMXrA4fpl5CnShCzF+cxk+El76wqwUTxckpHlGxsm9hDKLiL4Ce7oR/X7Z0PJTZjBn/cvkAdysMPoIq/8EcnTc0pYtw/8jCe2tVa8K0e6zevLt9U="
